name: tests

on:
  push:
  pull_request:

permissions:
  contents: read

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: pytest (py${{ matrix.python-version }})
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"]

    env:
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      PYTHONUNBUFFERED: "1"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Upgrade pip
        run: python -m pip install -U pip

      - name: Install test tooling (PHACC -> HA)
        run: python -m pip install --prefer-binary -r requirements.txt

      - name: Show resolved versions
        run: |
          python - <<'PY'
          try:
              import importlib.metadata as im
          except Exception:
              import importlib_metadata as im
          for pkg in ("homeassistant","pytest-homeassistant-custom-component","pytest"):
              try:
                  print(pkg, "=>", im.version(pkg))
              except Exception:
                  print(pkg, "=> NOT INSTALLED")
          PY

      - name: Run tests (fast-fail)
        run: pytest -q --maxfail=1
